import { Router } from "express";
import AssistantRouter from "./AssistantRouter";
// import AuthRouter from "./AuthRouter";
import ChatRouter from "./ChatRouter";
import ChunkRouter from "./ChunkRouter";
import ConfigRouter from "./ConfigRouter";
import DatasourceRouter from "./DatasourceRouter";
import DocumentsourceRouter from "./DocumentsourceRouter";
import EmbeddingRouter from "./EmbeddingRouter";
import FileUploadRouter from "./FileUploadRouter";
import HealthRouter from "./HealthRouter";
import IngestionRouter from "./IngestionRouter";
import IntegrationRouter from "./IntegrationRouter";
import MessageRouter from "./MessageRouter";
import RAGRouter from "./RAGRouter";
import ReferenceRouter from "./ReferenceRouter";
import SemanticSearchRouter from "./SemanticSearchRouter";
import TagRouter from "./TagRouter";
import ThreadRouter from "./ThreadRouter";
import UserRouter from "./UserRouter";
import WorkspaceRouter from "./WorkspaceRouter";
import TenantRouter from "./TenantRouter";

const IndexRouter = Router();

IndexRouter.use("/assistants", AssistantRouter);
// IndexRouter.use("/auth", AuthRouter);
IndexRouter.use("/chats", ChatRouter);
IndexRouter.use("/chunks", ChunkRouter);
IndexRouter.use("/configs", ConfigRouter);
IndexRouter.use("/datasources", DatasourceRouter);
IndexRouter.use("/documentsources", DocumentsourceRouter);
IndexRouter.use("/embeddings", EmbeddingRouter);
IndexRouter.use("/files", FileUploadRouter);
IndexRouter.use("/health", HealthRouter);
IndexRouter.use("/ingestions", IngestionRouter);
IndexRouter.use("/integrations", IntegrationRouter);
IndexRouter.use("/messages", MessageRouter);
IndexRouter.use("/rag", RAGRouter);
IndexRouter.use("/references", ReferenceRouter);
IndexRouter.use("/semantic-search", SemanticSearchRouter);
IndexRouter.use("/tags", TagRouter);
IndexRouter.use("/threads", ThreadRouter);
IndexRouter.use("/users", UserRouter);
IndexRouter.use("/workspaces", WorkspaceRouter);
IndexRouter.use("/tenants", TenantRouter);

export default IndexRouter;
