ALTER TABLE chunks
  ADD COLUMN IF NOT EXISTS position INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS length INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS overlap INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS hash TEXT,
  ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS idx_chunks_document_id_position
  ON chunks (document_id, position);

CREATE INDEX IF NOT EXISTS idx_chunks_hash
  ON chunks (hash);
